# Usa una imagen base de nginx
FROM nginx:alpine

# Copia archivos locales al contenedor
COPY ./html /usr/share/nginx/html

# Expone el puerto 80 para servir el sitio web
EXPOSE 80

# Comando por defecto para ejecutar
CMD ["nginx", "-g", "daemon off;"]
