name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Asegúrate de que este secreto esté configurado
          password: ${{ secrets.DOCKER_PASSWORD }}   # Asegúrate de que este secreto esté configurado

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .                                   # Contexto es la raíz del repositorio
          dockerfile: Dockerfile                       # Aquí especificamos que el Dockerfile está en la raíz
          push: true                                   # Habilitar para hacer push de la imagen
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-image-example:latest  # Etiqueta para la imagen
